### ISSUE TITLE
Example of devices returning battery health data

### ISSUE THREAD

**Issue by MikeManzo** [ambient-weather/api-docs#6] opened 2018-08-18 18:17 UTC
In the Device Data Specs we have the following that a device "might" send:

- battout - Good/Bad indication, String, 1=Good, 0=Bad
- batt1...batt10 - Good/Bad indication, String, 1=Good, 0=Bad

Looking at the API documentation, I don't see an example returning any of these parameters. In my case, my station (hooked up via Meteobridge) reports battery health just fine.  

Does the API handle battery health yet, or is this a case where my Meteobridge isn't reporting the data to Ambient?

Thx!

**Comment by ambientweather** [comment] 2018-08-20 17:35
Yes, the MeteoBridge does not send it to AmbientWeather.net
I can ask Boris, the author of the MeteoBridge, to add it.
It is part of our spec but not implemented.
Thanks
Ed

**Comment by owise1** [comment] 2018-12-07 19:13
Duplicate of #10

**Closed by owise1** 2018-12-07 19:13 UTC
